import { margin, padding, textAlign } from "@mui/system";

export const InputStyles = {
  backgroundColor: (theme) => theme.palette.secondary.light,
  borderRadius: "5px",
  "& .MuiInputBase-root": {
    paddingRight: 0,
  },
  "& .MuiInputBase-input:focus": {
    boxShadow: (theme) => `2px 3px 15px 0px ${theme.palette.primary[900]}`,
  },
  "& .MuiInputBase-root::after": {
    borderBottom: "none",
  },
};

export const ManagementFromStyles = {
  managementModal: {
    width: 750,
    height: 544,
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    borderRadius: "8px",
    backgroundColor: "text.light",
    color: "text.dark",
  },
  warningModal: {
    width: 400,
    height: 266,
    borderRadius: "8px",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    backgroundColor: "text.light",
    color: "text.dark",
    position: "absolute",
  },
  warningHeader: {
    width: "100%",
    height: "86px",
    padding: "16px 24px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  warningModalContent: {
    width: "100%",
    height: "74px",
    textAlign: "center",
  },
  warningModalButton: {
    width: "100%",
    height: "96px",
    display: "flex",
    justifyContent: "end",
    padding: "24px 36px",
    gap: "16px",
  },
  formHeader: {
    width: "100%",
    height: "88px",
    padding: "16px 0",
    position: "relative",
    marginBottom: "16px",
  },
  formContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    height: 368,
    borderTop: "2px solid",
    borderColor: "text.neutral",
  },
  inputField: {
    width: "321px",
   
    "& .MuiInputLabel-root": {
      fontSize: "16px",
      color: "text.secondary",
      position: "absolute",
      top: "-4px",
      left: "4px",
      "&.Mui-focused": {
        color: "primary.main",
      },
    },
    "& .MuiOutlinedInput-root": {
      height: "45px",
      "& fieldset": {
        borderColor: "text.dark",
        border: "2px solid",
      },
      "&:hover fieldset": {
        borderColor: "text.dark",
      },
      "&.Mui-focused fieldset": {
        borderColor: "primary.main",
      },
    },
    "& .MuiOutlinedInput-input": {
      padding: "10px 14px",
      fontSize: "16px",
      color: "text.dark",
    },
  },
  formColumn: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    width: 345,
    height: 288,
    padding: "12px",
    justifyContent: "center",
    margin: "16px",
  },
  imageContainer: {
    width: 345,
    height: 288,
    margin: "16px",
    padding: "12px",
    display: "flex",
    alignItems: "center",
  },
  imagePreview: {
    display: "flex",
    alignItems: "center",
    boxSizing: "border-box",
    border: "2px dashed #000000",
    color: "text.secondary",
    width: 321,
    height: 240,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    "&:hover": {
      backgroundColor: "text.light",
      color: "primary.main",
      border: "2px dashed",
      cursor: "pointer",
      borderColor: "primary.main",
      "& .MuiSvgIcon-root": {
        color: "primary.main",
      },
    },
  },
  buttonContainer: {
    display: "flex",
    justifyContent: "end",
    gap: "10px",
    padding: "12px 36px 40px 12px",
    height: 88,
  },
  addButton: {
    borderRadius: "5px",
    backgroundColor: "primary.main",
    color: "text.light",
    height: 36,
    width: 73,
    boxShadow: "2px 4px 10px rgba(0, 0, 0, 0.25)",
    fontSize: 12,
    textTransform: "none",
    "&:hover": {
      backgroundColor: "text.light",
      color: "primary.main",
      border: "2px solid",
      borderColor: "primary.main",
      "& .MuiSvgIcon-root": {
        color: "primary.main",
      },
    },
  },
  cancelButton: {
    borderRadius: "5px",
    color: "text.dark",
    border: "1px solid",
    borderColor: "text.neutral",
    height: 36,
    width: 73,
    boxShadow: "2px 4px 10px rgba(0, 0, 0, 0.25)",
    fontSize: 12,
    textTransform: "none",
    "&:hover": {
      backgroundColor: "text.light",
      color: "primary.main",
      border: "2px solid",
      borderColor: "primary.main",
    },
  },
  addIcon: {
    color: "text.light",
    width: "15px",
    height: "15px",
  },
  cancelDeleteButton: {
    width: "64px",
    height: "32px",
    padding: "8px 20px",
    fontSize: "12px",
    color: "text.secondary",
    boxShadow: "2px 4px 10px rgba(0, 0, 0, 0.25)",
    border: "1px solid",
    borderColor: "text.neutral",
    gap: "10px",
    borderRadius: "5px",
    "&:hover": {
      backgroundColor: "text.light",
      color: "primary.main",
      border: "2px solid",
      borderColor: "primary.main",
    },
  },
  deleteButton: {
    width: "64px",
    height: "32px",
    padding: "8px 20px",
    fontSize: "12px",
    backgroundColor: "primary.main",
    color: "text.light",
    border: "1px solid",
    borderColor: "primary.main",
    gap: "10px",
    borderRadius: "5px",
    boxShadow: "2px 4px 10px rgba(0, 0, 0, 0.25)",
    "&:hover": {
      backgroundColor: "text.light",
      color: "primary.main",
      border: "2px solid",
      borderColor: "primary.main",
    },
  },
};
