export const API_ENDPOINTS = {
  AUTH: {
    PROFILE: "auth/profile",
    LOGIN: "auth/login",
    LOGOUT: "auth/logout",
    REFRESH_TOKEN: "auth/refresh",
  },
  CLUBS: {
    GET_ALL: "/clubs",
    GET: `/clubs`,
    ADD: "/clubs",
    UPLOAD: `/local-files`,
    UPDATE: `/clubs`,
    DELETE: `/clubs`,
  },
  DEPARTMENTS: {
    GET_ALL: "/departments",
    GET: `/departments`,
    ADD: "/departments",
    UPLOAD: `/local-files`,
    UPDATE: `/departments`,
    DELETE: `/departments`,
  },
  STUDENTS: {
    GET_ALL: "/students",
    GET: `/students`,
    ADD: "/students",
    UPDATE: `/students`,
    DELETE: `/students`,
  },
  SEMESTERS: {
    GET_ALL: `/semesters`,
    GET: `/semesters`,
    NOW: `/semesters/now`,
    ADD: `/semesters`,
    UPDATE: `/semesters`,
    DELETE: `/semesters`,
  },
  EVENTS: {
    GET_ALL: `/events`,
    GET: `/events`,
    ADD: `/events`,
    UPDATE: `/events`,
    DELETE: `/events`,
  },
  EVENTS_POINT: {
    GET_ALL: `/event-point`,
    GET: `/event-point`,
    ADD: `/event-point`,
    UPDATE: `/event-point`,
    DELETE: `/event-point`,
  },
};
