import { Box, Avatar, Typography } from "@mui/material";
import EditIcon from "@mui/icons-material/Edit";
import { GridActionsCellItem } from "@mui/x-data-grid";
import { styles } from "../../components/DataTable/style";

export const columnsSchema = (handleEditClick) => {
  const columns = [
    {
      field: "id",
      headerName: "ID",
      headerClassName: "header",
      cellClassName: "cell",
      headerAlign: "left",
      type: "number",
      width: 50,
      align: "left",
      editable: false,
    },
    {
      field: "studentID",
      headerName: "MSSV",
      headerClassName: "header",
      cellClassName: "cell",
      type: "string",
      width: 200,
      editable: false,
    },
    {
      field: "studentName",
      headerName: "Họ và Tên",
      headerClassName: "header",
      cellClassName: "cell",
      renderCell: (params) => (
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            padding: "12px 18px 12px 0px",
            gap: "18px",
          }}
        >
          <Avatar src={params.row.avatar} alt="Avatar" sx={styles.avatar} />
          <Typography variant="body1" className="ml-[12px]">
            {params.value}
          </Typography>
        </Box>
      ),
      type: "string",
      width: 300,
      align: "left",
      headerAlign: "left",
      editable: false,
    },
    {
      field: "studyPoint",
      headerName: "Điểm cộng",
      headerClassName: "header",
      cellClassName: "cell",
      type: "number",
      headerAlign: "center",
      align: "left",
      width: 150,
      editable: false,
    },
    {
      field: "studyComment",
      headerName: "Comment",
      headerClassName: "header",
      cellClassName: "cell",
      type: "string",
      headerAlign: "center",
      align: "left",
      width: 200,
      editable: false,
    },
    {
      field: "totalStudyPoint",
      headerName: "Tổng điểm",
      headerClassName: "header",
      cellClassName: "cell",
      type: "number",
      headerAlign: "center",
      align: "left",
      width: 150,
      editable: false,
    },
    {
      field: "activityPoint1",
      headerName: "Điểm cộng(1)",
      headerClassName: "header",
      cellClassName: "cell",
      type: "number",
      headerAlign: "center",
      align: "left",
      width: 150,
      editable: false,
    },
    {
      field: "activityPoint2",
      headerName: "Điểm cộng(2)",
      headerClassName: "header",
      cellClassName: "cell",
      type: "number",
      headerAlign: "center",
      align: "left",
      width: 150,
      editable: false,
    },
    {
      field: "activityPoint3",
      headerName: "Điểm cộng(3)",
      headerClassName: "header",
      cellClassName: "cell",
      type: "number",
      headerAlign: "center",
      align: "left",
      width: 150,
      editable: false,
    },
    {
      field: "activityPoint4",
      headerName: "Điểm cộng(4)",
      headerClassName: "header",
      cellClassName: "cell",
      type: "number",
      headerAlign: "center",
      align: "left",
      width: 150,
      editable: false,
    },
    {
      field: "activityPoint5",
      headerName: "Điểm cộng(5)",
      headerClassName: "header",
      cellClassName: "cell",
      type: "number",
      headerAlign: "center",
      align: "left",
      width: 150,
      editable: false,
    },
    {
      field: "totalActivityPoint",
      headerName: "Tổng điểm",
      headerClassName: "header",
      cellClassName: "cell",
      type: "number",
      headerAlign: "center",
      align: "left",
      width: 150,
      editable: false,
    },
    {
      field: "citizenshipPoint",
      headerName: "Điểm cộng",
      headerClassName: "header",
      cellClassName: "cell",
      type: "number",
      headerAlign: "center",
      align: "left",
      width: 150,
      editable: false,
    },
    {
      field: "citizenshipComment",
      headerName: "Comment",
      headerClassName: "header",
      cellClassName: "cell",
      type: "string",
      headerAlign: "center",
      align: "left",
      width: 200,
      editable: false,
    },
    {
      field: "totalCitizenshipPoint",
      headerName: "Tổng điểm",
      headerClassName: "header",
      cellClassName: "cell",
      type: "number",
      headerAlign: "center",
      align: "left",
      width: 150,
      editable: false,
    },
    {
      field: "organizationPoint",
      headerName: "Điểm cộng",
      headerClassName: "header",
      cellClassName: "cell",
      type: "number",
      headerAlign: "center",
      align: "left",
      width: 150,
      editable: false,
    },
    {
      field: "organizationComment",
      headerName: "Comment",
      headerClassName: "header",
      cellClassName: "cell",
      type: "string",
      headerAlign: "center",
      align: "left",
      width: 200,
      editable: false,
    },
    {
      field: "totalOrganizationPoint",
      headerName: "Tổng điểm",
      headerClassName: "header",
      cellClassName: "cell",
      type: "number",
      headerAlign: "center",
      align: "left",
      width: 150,
      editable: false,
    },
    {
      field: "totalFinalPoint",
      headerName: "Tổng điểm",
      headerClassName: "header",
      cellClassName: "cell",
      type: "number",
      headerAlign: "center",
      align: "left",
      width: 100,
      editable: false,
    },
    {
      field: "classification",
      headerName: "Xếp loại",
      headerClassName: "header",
      cellClassName: "cell",
      type: "string",
      headerAlign: "center",
      align: "left",
      width: 100,
      editable: false,
    },
    {
      field: "actions",
      headerName: "Actions",
      headerClassName: "header lastHeader",
      cellClassName: "cell actions lastHeader",
      headerAlign: "center",
      align: "center",
      width: 150,
      renderCell: ({ row }) => (
        <GridActionsCellItem
          icon={<EditIcon />}
          onClick={() => handleEditClick(row)}
        />
      ),
    },
  ];

  return columns;
};

export const columnGroupingModel = [
  {
    groupId: "id",
    headerName: "",
    headerClassName: "majorHeader",
    children: [{ field: "id" }],
  },
  {
    groupId: "studentID",
    headerName: "",
    headerClassName: "majorHeader",
    children: [{ field: "studentID" }],
  },
  {
    groupId: "name",
    headerName: "",
    headerClassName: "majorHeader",
    children: [{ field: "name" }],
  },
  {
    groupId: "study",
    headerClassName: "majorHeader",
    headerName: "Đánh giá Ý thức học tập (Mặc định: 20; tối đa 35)",
    children: [
      { field: "studyPoint" },
      { field: "studyComment" },
      { field: "totalStudyPoint" },
    ],
  },
  {
    groupId: "activityPoint",
    headerName:
      "Đánh giá tham gia công tác chính trị (Mặc định: 20; tối đa 35)",
    headerClassName: "majorHeader",
    children: [
      { field: "activityPoint1" },
      { field: "activityPoint2" },
      { field: "activityPoint3" },
      { field: "activityPoint4" },
      { field: "activityPoint5" },
      { field: "totalActivityPoint" },
    ],
  },
  {
    groupId: "citizenship",
    headerClassName: "majorHeader",

    headerName:
      "Phẩm chất công dân và quan hệ cộng đồng (Điểm mặc định: 15, tối đa 25)",
    children: [
      { field: "citizenshipPoint" },
      { field: "citizenshipComment" },
      { field: "finalCitizenshipPoint" },
    ],
  },
  {
    groupId: "organizationPoint",
    headerName: "Đánh giá tham gia công tác phụ trách đoàn thể, các tổ chức…",
    headerClassName: "majorHeader",
    children: [
      { field: "organizationPoint" },
      { field: "organizationComment" },
      { field: "finalOrganizationPoint" },
    ],
  },
  {
    groupId: "totalFinalPoint",
    headerName: "",
    headerClassName: "majorHeader",
    children: [{ field: "totalFinalPoint" }],
  },
  {
    groupId: "classification",
    headerName: "",
    headerClassName: "majorHeader ",
    children: [{ field: "classification" }],
  },
  {
    groupId: "actions",
    headerName: "",
    headerClassName: "majorHeader lastHeader",
    children: [{ field: "actions" }],
  },
];
